# [START app_yaml]
runtime: nodejs20

service: service

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 20

handlers:
  - url: /.*
    secure: always
    script: auto
# [END app_yaml]
