name: Release
description: Release nextjs app to GAE

inputs:
  SA_JSON:
    description: 'Service Account JSON'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Setup Google App Engine Folder
      run: |
        cp -r .next/standalone .
        cp -r .next/static standalone/.next/
        cp -r public standalone/
        cp app.yaml standalone/
        cd standalone
        mv node_modules node_module_hack
        echo ".git" > .gcloudignore
        ls -a
        cat > package.json << EOL
        {
          "name": "wl_service_schedule",
          "version": "production",
          "private": true,
          "scripts": {
            "install": "ls; mv -fn node_module_hack node_modules",
            "start": "node server.js"
          }
        }
        EOL
        npm install
      shell: bash

    - name: Authenticate with gcloud
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ inputs.SA_JSON }}"
    
    - name: Debug
      run: |
        ls
        ls standalone
      shell: bash

    - name: Deploy to App Engine
      uses: "google-github-actions/deploy-appengine@v1"
      with:
        working_directory: standalone
