name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SA_JSON }}'

      - name: Replace secrets in file
        run: |
          sed -i "s|YOUR_GOOGLE_DRIVE_ENDPOINT|${{ secrets.GOOGLE_DRIVE_ENDPOINT }}|g" .env.local.template
          sed -i "s|YOUR_GOOGLE_CLIENT_EMAIL|${{ secrets.GOOGLE_CLIENT_EMAIL }}|g" .env.local.template
          sed -i "s|YOUR_GOOGLE_PRIVATE_KEY|${{ secrets.GOOGLE_PRIVATE_KEY }}|g" .env.local.template
          sed -i "s|YOUR_GOOGLE_SPREAD_SHEET_ID|${{ secrets.MAIN_SPREAD_SHEET_ID }}|g" .env.local.template

      - name: Rename file
        run: mv .env.local.template .env.local

      - name: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
