name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SA_JSON }}'

      # - name: Set .env.local
      #   run: |
      #     touch .env.local
      #     secrets_value="${{ secrets.GOOGLE_PRIVATE_KEY }}"
      #     printf "GOOGLE_SECRECT_KEY=%s\n" "$secrets_value" > .env.local

      - run: echo "Value of GOOGLE_PRIVATE_KEY"
        env:
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

      - run: |
          touch .env.local
          echo "GOOGLE_SECRECT_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> .env.local


      - name: Deploy
        uses: 'google-github-actions/deploy-appengine@v1'
