name: CD

on:
  push:
    branches:
      - "#23/feature/be_a_CD_Player"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace secrets in .env.local.template
        run: |
          sed -e "s/YOUR_GOOGLE_DRIVE_ENDPOINT/${{ secrets.YOUR_GOOGLE_DRIVE_ENDPOINT }}/g" \
              -e "s/YOUR_GOOGLE_CLIENT_EMAIL/${{ secrets.YOUR_GOOGLE_CLIENT_EMAIL }}/g" \
              -e "s/YOUR_GOOGLE_PRIVATE_KEY/${{ secrets.YOUR_GOOGLE_PRIVATE_KEY }}/g" \
              -e "s/YOUR_GOOGLE_SPREAD_SHEET_ID/${{ secrets.YOUR_GOOGLE_SPREAD_SHEET_ID }}/g" \
              .env.local.template > .env.local

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SA_JSON}}'
          service_account: 'lowking@wl-service-schedule.iam.gserviceaccount.com'
      
      - name: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
