name: CD

on:
  push:
    branches:
      - "#23/feature/be_a_CD_Player"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SA_JSON}}'
          service_account: 'lowking@wl-service-schedule.iam.gserviceaccount.com'
      
      - name: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
