name: Release Please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip-github-release:
        description: 'Skip creating a GitHub release'
        required: false
        type: boolean
        default: false
      skip-github-pull-request:
        description: 'Skip creating a GitHub pull request'
        required: false
        type: boolean
        default: false

jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - name: Check commit message
          if: ${{ github.event_name == 'push' }}
          run: |
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            if [[ "$COMMIT_MESSAGE" != release:* ]]; then
              echo "Skipping release action because commit does not start with 'release:'."
              exit 0
            fi
        - uses: googleapis/release-please-action@v4
          with:
            token: ${{ secrets.RELEASE_PLEASE_TOKEN }}